version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: maven-source-plugin
        versions: [3.3.0]