version: "3.3"
services:
  ldes-server:
    container_name: basic_ldes-server
    image: 300765198237d66902600e6af689ad566e3e0d4648ffac346e6b4f7ddb56d717
    environment:
      - SPRING_CONFIG_LOCATION=/config/
      - PYROSCOPE_CONFIGURATION_FILE=/config/pyroscope.properties
    volumes:
      - ./docker-compose/server.config.yml:/config/application.yml:ro
      - ./docker-compose/pyroscope.properties:/config/pyroscope.properties:ro
    ports:
      - 8080:8080
    networks:
      - ldes
    depends_on:
      - ldes-mongodb
  ldes-mongodb:
    container_name: ldes-mongodb
    image: mongo:6.0.4
    ports:
      - 27017:27017
    networks:
      - ldes
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - 4040:4040
    networks:
      - ldes

  grafana:
    image: grafana/grafana:main
    ports:
      - 3000:3000
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph
    networks:
      - ldes
  jaeger:
    image: jaegertracing/all-in-one:1.37
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4319:4317"
      - "4320:4318"
      - "14250:14250"
networks:
  ldes: