springdoc:
  swagger-ui:
    path: /v1/swagger
ldes-server:
  host-name: "http://localhost:8080"
  use-relative-url: true
  ingest:
    port: 8089
  fetch:
    port: 8088
  admin:
    port: 8087
management:
  tracing:
    enabled: false
  endpoints:
    web:
      exposure:
        include:
          - prometheus
pyroscope:
  agent:
    enabled: true
spring:
  data:
    mongodb:
      database: ldes
      host: ldes-mongodb
      port: 27017
      auto-index-creation: true
#server:
#  servlet:
#    context-path: /ldes